<a href="https://colab.research.google.com/github/rezakhanahmadi342341/projects/blob/main/Extract_hand_writting_digits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
from PIL import Image
from google import genai

# List to store the numbers extracted from the image
n = []

def convert_image_to_CSV(img_path):
    # Open the image using PIL
    img = Image.open(img_path)

    # Initialize the genai client
    client = genai.Client(api_key="AIzaSyAFUv6OhsJKj1LY9WWtmx80wv1C_KjrqZ8")

    # Request the model to generate content from the image
    response = client.models.generate_content(
        model='gemini-1.5-flash',
        contents=[img, 'just give me the numbers of this image']
    )

    # Extract the text response containing numbers
    res = response.text

    # Split the response into numbers and convert to integers
    number_list = res.split()
    n.append([int(i) for i in number_list])

    # Create a DataFrame from the stored numbers
    df = pd.DataFrame(np.array(n), columns=[f'digit{i+1}' for i in range(len(number_list))])

    # Print the DataFrame
    return df

# Example usage
convert_image_to_CSV('/content/453726ef-2983-486e-8c7b-94b395c5a65a.png')

,digit1,digit2,digit3,digit4,digit5,digit6,digit7,digit8,digit9,digit10,digit11,digit12
0,2,1,1,3,5,0,6,5,1,0,9,3